name: csg4-forumestudantil-python

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Install AWS CLI 2
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --update

      # Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - uses: actions/checkout@v2
      - name: Terraform infra provisioning
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.3.7"
      
      - name: Terraform init
        run: terraform init
        working-directory: ./infra

      - name: Terraform apply
        run: terraform apply --auto-approve
        working-directory: ./infra

      - name: AWS Deploy push
        working-directory: .
        run: |
          aws deploy push \
          --application-name csg4-forumestudantil-application \
          --ignore-hidden-files \
          --s3-location s3://csg4-forumestudantil-codedeploy-deployments/csg4-forumestudantil-deployment-${{ github.sha }}.zip \
          --source .

      - name: AWS Create Deployment
        working-directory: .
        run: |
          aws deploy create-deployment \
          --application-name csg4-forumestudantil-application \
          --deployment-config-name CodeDeployDefault.OneAtATime \
          --deployment-group-name csg4-forumestudantil-deployment-group \
          --file-exists-behavior OVERWRITE \
          --s3-location bucket=csg4-forumestudantil-codedeploy-deployments,key=csg4-forumestudantil-deployment-${{ github.sha }}.zip,bundleType=zip \